name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Install musl and OpenSSL for Linux musl builds
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools libssl-dev pkg-config

      - name: Install mingw for Windows builds
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary with target
        run: |
          BINARY_NAME="r2-cli"
          FILE_NAME="r2-cli-${{ matrix.target }}"
          EXTENSION=""
          if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]; then
            EXTENSION=".exe"
          fi
          mv target/${{ matrix.target }}/release/$BINARY_NAME$EXTENSION target/${{ matrix.target }}/release/$FILE_NAME$EXTENSION

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target }}/release/r2-cli-${{ matrix.target }}${{ matrix.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary with target
        run: |
          BINARY_NAME="r2-cli"
          FILE_NAME="r2-cli-${{ matrix.target }}"
          mv target/${{ matrix.target }}/release/$BINARY_NAME target/${{ matrix.target }}/release/$FILE_NAME

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target }}/release/r2-cli-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
